### ISSUE TITLE
are '(' ')' actually invalid?

### ISSUE THREAD

**Issue by hellovai** [letsago/Coding-Projects#16]
https://github.com/letsago/Coding-Projects/blob/d33d41edd00299c6992eac431feb8698d1f131c9/Practice/PigLatin/piglatin.cpp#L39

**Comment by letsago** [comment]
Yup, according to the PigLatin translator, which I based my rules on, parentheses are considered invalid characters.

https://lingojam.com/PigLatinTranslator
