### ISSUE TITLE
Lets not handle this case. 

### ISSUE THREAD

**Issue by hellovai** [letsago/Coding-Projects#4]
https://github.com/letsago/Coding-Projects/blob/d33d41edd00299c6992eac431feb8698d1f131c9/Practice/PigLatin/headers/myvector_class.h#L80

If someone passes in something more than our size, we can just return false.

**Comment by letsago** [comment]
Right now, I'm using this case for when inserting a value exceeds the current array_size but not necessarily the memory_size. Often, inserting characters for PigLatin will cause array_size to increase past its old value but not necessarily past the memory_size.
